// constants.js

export const categories = [
  { id: 'fresh-produce', name: 'Fresh Produce', imageUrl: 'https://picsum.photos/seed/produce/600/400' },
  { id: 'dairy-eggs', name: 'Dairy & Eggs', imageUrl: 'https://picsum.photos/seed/dairy/600/400' },
  { id: 'meat-seafood', name: 'Meat & Seafood', imageUrl: 'https://picsum.photos/seed/meat/600/400' },
  { id: 'bakery', name: 'Bakery', imageUrl: 'https://picsum.photos/seed/bakery/600/400' },
  { id: 'health-wellness', name: 'Health & Wellness', imageUrl: 'https://picsum.photos/seed/wellness/600/400' },
  { id: 'baby-care', name: 'Baby Care', imageUrl: 'https://picsum.photos/seed/baby/600/400' },
  { id: 'rice-products', name: 'Rice & Rice Products', imageUrl: 'https://picsum.photos/seed/rice/600/400' },
  { id: 'beverages', name: 'Beverages', imageUrl: 'https://picsum.photos/seed/beverages/600/400' },
  { id: 'snacks-store', name: 'Snacks Store', imageUrl: 'https://picsum.photos/seed/snacks/600/400' },
  { id: 'cleaning-household', name: 'Cleaning & Household', imageUrl: 'https://picsum.photos/seed/cleaning/600/400' },
  { id: 'beauty-hygiene', name: 'Beauty & Hygiene', imageUrl: 'https://picsum.photos/seed/hygiene/600/400' },
  { id: 'home-kitchen', name: 'Home & Kitchen', imageUrl: 'https://picsum.photos/seed/kitchen/600/400' },
];

export const products = [
  // Existing Products
  {
    id: 1,
    brand: 'Fresho',
    name: 'Organic Avocados',
    price: 180,
    originalPrice: 220,
    imageUrl: 'https://picsum.photos/seed/avocado/400/400',
    category: 'Fresh Produce',
    description:
      'Creamy and delicious organic Hass avocados, perfect for toast or guacamole.',
    deliveryTime: '15 MINS',
    unit: '2 pcs',
    offerTag: 'Best Value',
  },
  {
    id: 2,
    brand: 'HappyFarm',
    name: 'Cage-Free Brown Eggs',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/eggs/400/400',
    category: 'Dairy & Eggs',
    description:
      'One dozen large brown cage-free eggs from pasture-raised hens.',
    deliveryTime: '10 MINS',
    unit: '12 pcs',
  },
  {
    id: 3,
    brand: 'OceanCatch',
    name: 'Wild-Caught Salmon',
    price: 850,
    originalPrice: 999,
    imageUrl: 'https://picsum.photos/seed/salmon/400/400',
    category: 'Meat & Seafood',
    description:
      'Fresh, wild-caught sockeye salmon fillet. Rich in Omega-3s.',
    deliveryTime: '30 MINS',
    unit: '500g',
    offerTag: 'Har Din Sasta!',
  },
  {
    id: 4,
    brand: 'The Bakehouse',
    name: 'Sourdough Loaf',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/sourdough/400/400',
    category: 'Bakery',
    description:
      'Artisan-baked sourdough bread with a crispy crust and chewy interior.',
    deliveryTime: 'ASAP',
    unit: '1 loaf',
  },
  {
    id: 5,
    brand: 'Pampers',
    name: 'Baby Wipes',
    price: 138,
    originalPrice: 299,
    imageUrl: 'https://picsum.photos/seed/pampers/400/400',
    category: 'Baby Care',
    description: 'Gentle and effective baby wipes for your little one.',
    deliveryTime: '5 MINS',
    unit: '72 pcs',
    offerTag: 'Har Din Sasta!',
  },
  {
    id: 6,
    brand: "Little's",
    name: 'Soft Cleansing Extra Thick & Moist Wipes',
    price: 80,
    originalPrice: 190,
    imageUrl: 'https://picsum.photos/seed/littles/400/400',
    category: 'Baby Care',
    description: 'Extra thick and moist wipes for a thorough clean.',
    deliveryTime: '5 MINS',
    unit: '80 pcs',
  },
  {
    id: 7,
    brand: 'bigbasket',
    name: 'Fresh Baby Wipes',
    price: 82,
    originalPrice: 199,
    imageUrl: 'https://picsum.photos/seed/bbwipes/400/400',
    category: 'Baby Care',
    description: "bigbasket's own brand of fresh and gentle baby wipes.",
    deliveryTime: '5 MINS',
    unit: '80 pcs',
    offerTag: 'Har Din Sasta!',
  },
  {
    id: 8,
    brand: 'bigbasket',
    name: 'Cherry Blossom Baby Wipes',
    price: 82,
    originalPrice: 199,
    imageUrl: 'https://picsum.photos/seed/cherrywipes/400/400',
    category: 'Baby Care',
    description: 'Infused with a gentle cherry blossom fragrance.',
    deliveryTime: '5 MINS',
    unit: '80 pcs',
  },
  // New Products
  {
    id: 9,
    brand: 'India Gate',
    name: 'Basmati Rice - Feast Rozzana',
    price: 849,
    imageUrl: 'https://picsum.photos/seed/basmati/400/400',
    category: 'Rice & Rice Products',
    description:
      'Aged basmati rice for daily cooking. Perfect for biryani and pulao.',
    deliveryTime: '20 MINS',
    unit: '5 kg',
  },
  {
    id: 10,
    brand: 'Daawat',
    name: 'Brown Basmati Rice',
    price: 215,
    imageUrl: 'https://picsum.photos/seed/brownrice/400/400',
    category: 'Rice & Rice Products',
    description: 'Wholegrain brown basmati rice, a healthier alternative.',
    deliveryTime: '20 MINS',
    unit: '1 kg',
  },
  {
    id: 11,
    brand: 'Coca-Cola',
    name: 'Coke Zero',
    price: 40,
    imageUrl: 'https://picsum.photos/seed/coke/400/400',
    category: 'Beverages',
    description: 'The great taste of Coca-Cola with zero sugar.',
    deliveryTime: '5 MINS',
    unit: '300 ml',
  },
  {
    id: 12,
    brand: 'Tropicana',
    name: '100% Orange Juice',
    price: 135,
    imageUrl: 'https://picsum.photos/seed/juice/400/400',
    category: 'Beverages',
    description: 'Pure, unsweetened orange juice to kickstart your day.',
    deliveryTime: '10 MINS',
    unit: '1 L',
  },
  {
    id: 13,
    brand: 'Lays',
    name: "India's Magic Masala",
    price: 20,
    imageUrl: 'https://picsum.photos/seed/lays/400/400',
    category: 'Snacks Store',
    description:
      'Classic potato chips with a spicy Indian masala flavour.',
    deliveryTime: '5 MINS',
    unit: '52 g',
  },
  {
    id: 14,
    brand: 'Britannia',
    name: 'Good Day Cashew Cookies',
    price: 45,
    imageUrl: 'https://picsum.photos/seed/cookies/400/400',
    category: 'Snacks Store',
    description: 'Buttery cookies filled with real cashew nuts.',
    deliveryTime: '10 MINS',
    unit: '200 g',
  },
  {
    id: 15,
    brand: 'Harpic',
    name: 'Disinfectant Toilet Cleaner',
    price: 198,
    imageUrl: 'https://picsum.photos/seed/harpic/400/400',
    category: 'Cleaning & Household',
    description: 'Kills 99.9% of germs and removes tough stains.',
    deliveryTime: '30 MINS',
    unit: '1 L',
  },
  {
    id: 16,
    brand: 'Surf Excel',
    name: 'Matic Top Load Liquid Detergent',
    price: 220,
    imageUrl: 'https://picsum.photos/seed/surf/400/400',
    category: 'Cleaning & Household',
    description:
      'Powerful liquid detergent for top load washing machines.',
    deliveryTime: '30 MINS',
    unit: '1 L',
  },
  {
    id: 17,
    brand: 'Dove',
    name: 'Cream Beauty Bathing Bar',
    price: 64,
    imageUrl: 'https://picsum.photos/seed/dove/400/400',
    category: 'Beauty & Hygiene',
    description: 'Moisturizing bar soap for soft, smooth skin.',
    deliveryTime: '15 MINS',
    unit: '125 g',
  },
  {
    id: 18,
    brand: 'Colgate',
    name: 'MaxFresh Toothpaste',
    price: 95,
    imageUrl: 'https://picsum.photos/seed/colgate/400/400',
    category: 'Beauty & Hygiene',
    description: 'Cooling crystals for an intensely fresh breath.',
    deliveryTime: '10 MINS',
    unit: '150 g',
  },
  {
    id: 19,
    brand: 'Prestige',
    name: 'Omega Deluxe Granite Fry Pan',
    price: 899,
    imageUrl: 'https://picsum.photos/seed/pan/400/400',
    category: 'Home & Kitchen',
    description: 'Durable non-stick fry pan for healthy cooking.',
    deliveryTime: 'ASAP',
    unit: '1 pc',
  },
  {
    id: 20,
    brand: 'Cello',
    name: 'Checkers PET Canister Set',
    price: 450,
    originalPrice: 650,
    imageUrl: 'https://picsum.photos/seed/canister/400/400',
    category: 'Home & Kitchen',
    description:
      'Airtight storage containers to keep your kitchen organized.',
    deliveryTime: 'ASAP',
    unit: 'Set of 3',
    offerTag: 'Best Value',
  },
  {
    id: 21,
    brand: 'Lipton',
    name: 'Green Tea, Pure & Light',
    price: 160,
    imageUrl: 'https://picsum.photos/seed/greentea/400/400',
    category: 'Beverages',
    description: 'Refreshing and light green tea bags.',
    deliveryTime: '10 MINS',
    unit: '25 bags',
  },
  {
    id: 22,
    brand: 'Oreo',
    name: 'Chocolate Creme Biscuit',
    price: 30,
    imageUrl: 'https://picsum.photos/seed/oreo/400/400',
    category: 'Snacks Store',
    description:
      'The classic oreo with a rich chocolate creme filling.',
    deliveryTime: '5 MINS',
    unit: '120 g',
  },
  {
    id: 23,
    brand: 'Lizol',
    name: 'Disinfectant Surface Cleaner',
    price: 185,
    imageUrl: 'https://picsum.photos/seed/lizol/400/400',
    category: 'Cleaning & Household',
    description:
      'Cleans and disinfects all washable surfaces in your home.',
    deliveryTime: '30 MINS',
    unit: '975 ml',
  },
  {
    id: 24,
    brand: 'Head & Shoulders',
    name: 'Anti-Dandruff Shampoo',
    price: 180,
    imageUrl: 'https://picsum.photos/seed/shampoo/400/400',
    category: 'Beauty & Hygiene',
    description:
      'Cool menthol shampoo that leaves your scalp feeling fresh.',
    deliveryTime: '15 MINS',
    unit: '180 ml',
  },
  {
    id: 25,
    brand: 'Optimum Nutrition',
    name: 'Gold Standard 100% Whey Protein',
    price: 3500,
    originalPrice: 4200,
    imageUrl: 'https://picsum.photos/seed/protein/400/400',
    category: 'Health & Wellness',
    description:
      '24g of whey protein with low levels of fat, cholesterol, lactose and other stuff you can do without.',
    deliveryTime: 'ASAP',
    unit: '2 lbs',
    offerTag: 'Top Seller',
  },
  {
    id: 26,
    brand: 'MuscleTech',
    name: 'Mass-Tech Elite - Mass Gainer',
    price: 2800,
    imageUrl: 'https://picsum.photos/seed/massgainer/400/400',
    category: 'Health & Wellness',
    description:
      'Advanced muscle mass gainer for those who have struggled with adding size.',
    deliveryTime: 'ASAP',
    unit: '7 lbs',
  },
  {
    id: 27,
    brand: 'Carbamide Forte',
    name: 'Multivitamin for Men',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://picsum.photos/seed/multivitamin/400/400',
    category: 'Health & Wellness',
    description:
      'With 67 ingredients and 13 vital blends to support immunity, energy, and digestion.',
    deliveryTime: '1 DAY',
    unit: '60 tablets',
  },
];
